### ISSUE TITLE
What is secureuxtheme_uninstall() returned 00000000

### ISSUE THREAD

**Issue by InnerSanctuary** [namazso/SecureUxTheme#189] opened 2024-06-05 23:21 UTC
When clicking the uninstall button i get:

1717629575150 > Uninstall started...
1717629575152 > secureuxtheme_uninstall() returned 00000000

Anyone know what this means?  Was it uninstalled?

**Comment by RaXorX** [comment] 2024-06-07 07:19
I had to try this because I was having issues with some themes. Clicking on Uninstall and then rebooting, I couldn't apply any themes anymore. Switching to dark/night or day type themes just changed Windows theme to dark and light respectively and the wallpapers/mouse pointers from that theme but not the theme style itself.

So clearly seemed to have uninstalled perhaps. But the weird thing is that after I reinstalled, it's still the same. Reinstalled, rebooted and doesn't work anymore. 

Running Windows 11 IoT LTSC 26100.712

But the themes worked when I had done an in-upgrade from Windows 11 Enterprise where secureux was working fine. After the upgrade it was still working fine as well.

**Comment by QuiteAFancyEmerald** [comment] 2024-07-27 16:54
I have the same issue on Windows 11 IoT LTSC

**Comment by QuiteAFancyEmerald** [comment] 2024-08-22 03:28
I have found a solution to the problem; essentially run/install SecureUXTheme but use Winaero Theme Switcher to apply the actual theme. Why does this work?

Essentially it directly changes the registry to allow themes.

```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\ThemeSwitcher.exe]
"VerifierDlls"="SecureUxTheme.dll"
"GlobalFlag"=dword:00000100
```

https://winaero.com/winaero-theme-switcher/

**Comment by furquim87** [comment] 2024-10-01 20:42
> I have found a solution to the problem; essentially run/install SecureUXTheme but use Winaero Theme Switcher to apply the actual theme. Why does this work?
> 
> Essentially it directly changes the registry to allow themes.
> 
> ```
> Windows Registry Editor Version 5.00
> 
> [HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\ThemeSwitcher.exe]
> "VerifierDlls"="SecureUxTheme.dll"
> "GlobalFlag"=dword:00000100
> ```
> 
> https://winaero.com/winaero-theme-switcher/

This doesn't seem to be fully working for me. While it does apply the theme to some UI elements, it won't apply to the system explorer. Unfortunately I'm having to use UltraUXThemePatcher until I can find a fix for this issue, or the developer updates this project.

**Comment by namazso** [comment] 2024-10-12 10:40
0 means success, this works as intended

**Closed by namazso** 2024-10-12 10:40 UTC
