### ISSUE TITLE
Themes Not Fully Applying

### ISSUE THREAD

**Issue by SelfAfflicted** [namazso/SecureUxTheme#95] opened 2022-03-01 21:35 UTC
I tried 3 different themes, from the same author, and none would fully change my system, only some colors and title bar's minmize/maximize/close buttons changed. I don't I'm probably doing something wrong, anyway, if you need any other info, let me know.

![image](https://user-images.githubusercontent.com/13339406/156251424-c1850699-0fbe-43e7-b5af-66ae7ede964e.png)
```
1646168093322 > Version v2.1.2
1646168093326 > Running on 10.0.19042 flavor F
1646168093330 > MainDialog: is_elevated 0
1646168093333 > Session user: Jeremy Process user: Jeremy
1646168093429 > UpdatePatcherState: file_has_content 1 file_is_same 1 file_error 0 is_loaded 1
1646168097977 > ApplyTheme(9)
1646168097979 > PatchThemeInternal(9)
1646168104552 > ApplyTheme: SetCurrentTheme returned 00000000
1646168375439 > ApplyTheme(9)
1646168375442 > PatchThemeInternal(9)
1646168375446 > ApplyTheme: SetCurrentTheme returned 00000000
1646169057975 > ApplyTheme(1)
1646169057982 > PatchThemeInternal(1)
1646169062992 > ApplyTheme: SetCurrentTheme returned 00000000
```

[Themes.zip](https://github.com/namazso/SecureUxTheme/files/8164880/Themes.zip)

**Comment by namazso** [comment] 2022-03-01 21:44
pretty sure only BIB3 from niivu has a full dark mode thingy, although I didnt check your files yet so it's just a stab in the dark

**Comment by SelfAfflicted** [comment] 2022-03-02 03:32
Honestly, I'm not even sure which are fully dark, not with the single preview image, nor any description on deviantart, but BIB was the one I really wanted to use. When it failed I tried a couple more of theirs, only to be met with the same results. If your tool is working as intended, guess I'm just unlucky.

**Comment by enoversum** [comment] 2022-03-24 22:45
Since the latest update (Windows Insider Beta), my BIB3 is broken as well. Parts of the UI are now showing in white, so I assume Microsoft did change something in their latest Preview.

**Comment by Woesch-Nich** [comment] 2022-04-02 04:12
> Since the latest update (Windows Insider Beta), my BIB3 is broken as well. Parts of the UI are now showing in white, so I assume Microsoft did change something in their latest Preview.

Second that, context menus are now bugged in newest Win 11 Insider Beta. And Themes are not applying on the top part of the windows. 
![Screenshot_40](https://user-images.githubusercontent.com/81884360/161365787-8735369b-1a76-43b8-83d1-f25afde13f3e.png)

**Comment by enoversum** [comment] 2022-04-02 18:40
@Woesch-Nich We had this some months ago when Windows 11 Insider Previews introduced some newly themed elements, which caused trouble with minimising and maximising apps and settings windows. The solution was to wait until theme devs picked it up and fixed it in their themes. I assume this is the same problem here, and we probably won't see any changes until those features are being released in autumn and niivu is going to change his themes accordingly :) .

**Comment by ctthomas** [comment] 2022-04-17 23:27
So is this just the theme, or is the actual SecureUX not working as intended? I wasn't able to get my dracula theme by niivu to apply correctly, either.

**Comment by namazso** [comment] 2022-04-17 23:29
Almost certainly theme. SecureUxTheme failing usually results in nothing besides colors working, that's pretty easy to see. If you have at least something working like the close icon, it's probably a theme issue. Theme developers usually don't update their themes for insider previews because they change rapidly

**Comment by xctt** [comment] 2022-04-17 23:49
@namazso by chance, do you know of a dracula theme that works?

**Comment by namazso** [comment] 2022-04-18 00:05
No, I don't use Insider releases.

**Comment by xctt** [comment] 2022-04-18 00:19
I'm actually not on an Insider release. 

Version	10.0.22000 Build 22000

**Comment by namazso** [comment] 2023-07-12 19:11
Original issue was solved, so closing this.

**Comment by enoversum** [comment] 2023-07-12 19:12
Liebe KundInnen, KollegInnen und FreudInnen,

ich bin bis einschließlich 14. Juli im Kurzurlaub und kümmere mich gern nach meiner Rückkehr um Ihr Anliegen. In ausschließlich dringenden Fällen können Sie mich telefonisch erreichen. Die E-Mails werden bis dahin weder gelesen noch weitergeleitet.


Mit den besten Grüßen

Der halbautomatische Mailbeantworter von Eno Thiemann

**Closed by namazso** 2023-07-12 19:11 UTC
