### ISSUE TITLE
ERROR USING WINDOWS 8.1 !!!!!!!

### ISSUE THREAD

**Issue by EngrishGuysTaig** [namazso/SecureUxTheme#32] opened 2020-10-26 21:37 UTC
Well i have a problem with the lasted version and Windows 8.1, see ?
![Li](https://user-images.githubusercontent.com/73356571/97231468-c7112b80-17db-11eb-87d1-5604e8ed839b.PNG)
Please help if you can !

**Comment by EngrishGuysTaig** [comment] 2020-10-26 21:38
(yup that french)

**Comment by namazso** [comment] 2020-10-27 03:34
duplicate of #26

**Closed by namazso** 2020-10-27 03:34 UTC
