### ISSUE TITLE
Windows doesn't save Themes after Restart

### ISSUE THREAD

**Issue by benrunner** [namazso/SecureUxTheme#10] opened 2020-04-16 08:31 UTC
My problem is that after every restart the color of my theme is saved but everything else like the custom buttons are not saved. And additionally to that the LogonUI fix is not working as well, because my Task Manager Window is still white allthough i use a Dark Theme.

**Comment by namazso** [comment] 2020-04-19 08:19
are you sure SecureUxTheme is installed? Did you reboot too before setting a theme? Sounds like you just used ThemeTool which temporarily bypasses some parts and isn't meant to be used without SecureUxTheme installed and loaded.

do you have SecureUxTheme.dll in system32?

could you provide exact Windows version?

**Comment by benrunner** [comment] 2020-04-19 15:26
I started the SecureUxTheme_setup.exe and clicked on install and then reboooted my PC. My Windows Version is 1909 (Build 18363.720) and i got the SecureUxTheme.dll in system32.

**Comment by namazso** [comment] 2020-04-19 15:31
Hm.. that version is exactly the same as one of my test VMs.

How did you apply the theme?

Do you have SecureUxTheme.dll loaded into winlogon.exe? (if you don't know what this means, get Process Hacker, go to properties of the "winlogon.exe", then Modules tab, should look like this:)
![image](https://user-images.githubusercontent.com/8676443/79692084-813f3d80-8263-11ea-8df9-7d4998e46351.png)

**Comment by benrunner** [comment] 2020-04-19 16:08
![Unbenannt](https://user-images.githubusercontent.com/28601750/79693035-b39f6980-8268-11ea-9bec-fdd677b79e1a.PNG)

i downlaoded Process Hacker and i can find the SecureUxTheme.dll in my winlogon.exe ^^

**Comment by namazso** [comment] 2020-04-19 16:15
Weird, that means already set themes shouldn't be rejected on startup.

How are you setting the theme?

**Comment by benrunner** [comment] 2020-04-19 16:39
i first put the .msstyles via Drag&Drop to the SecureUxTheme window and then set my Theme (from C:\Windows\Resources\Themes\ ) in the Windows 10 Design-Settings. When i do this now nothing from the custom theme will be applied... only the ThemeTool is working for me :(

**Comment by benrunner** [comment] 2020-04-19 16:50
windows 10 did a update earlier. and got now the build 18363.778 ... could that be a problem?

**Comment by namazso** [comment] 2020-04-19 16:50
So, ThemeTool works all fine?
If so, I'd recommend keeping at that, the others are kind of hit or miss.

For themes in Settings to work you also need to have "Hook SystemSettings" enabled btw.

> windows 10 did a update earlier. and got now the build 18363.778 ... could that be a problem?

shouldn't really matter that much

**Comment by benrunner** [comment] 2020-04-19 17:48
> For themes in Settings to work you also need to have "Hook SystemSettings" enabled btw.
ok now i understand what hook SystemSettings does ^^

ok it seems that there is no other way than set the theme after every restart

but thank u so much for trying to figure out my problem ^^

**Comment by benrunner** [comment] 2020-04-22 18:17
Update: for me it helped to take Ownership of SecureUxTheme.dll, UXinit.dll, uxtheme and themeui.dll.

**Comment by namazso** [comment] 2020-04-23 09:28
that shouldn't change a thing, except maybe if for some reason the user in question didn't have read access to SecureUxTheme.dll, but that shouldn't even be possible, even more so because on failure it would just login-loop.

anyways, glad you solved it. Since I can't reproduce it nor can explain why that solution worked for you, I'm going to close this. If someone faces the same problem, feel free to open a new issue.

**Closed by namazso** 2020-04-23 09:28 UTC
