### ISSUE TITLE
Themes are not applied in latest windows build

### ISSUE THREAD

**Issue by Darkorz** [namazso/SecureUxTheme#19] opened 2020-07-15 15:45 UTC
I updated to Windows version 19041.388 and whilst the tool seem to install fine, all themes I've tried (including the one used as an example) do not work. There is no error but 90% of the theme is not applied (it swaps windows color but not much else). These themes were working fine on a previous install with last month's Windows build. If it's the themes themselves that need updating and this tool is working fine then feel free to close this issue.

**Comment by namazso** [comment] 2020-07-15 16:13
I have that update pending on my main machine, so I'll test it in some minutes

**Comment by namazso** [comment] 2020-07-15 16:25
Interesting, it works on my machine. Probably a dupe of #14 or #18 which I haven't managed to reproduce yet, although I'll try that again

**Comment by namazso** [comment] 2020-07-15 16:33
In the meantime, could you check if:
- SecureUxTheme.dll exists in system folder
- `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\winlogon.exe` in regedit shows `VerifierDlls` with a value of `SecureUxTheme.dll` and `GlobalFlag` with a value of `0x100` like this:

![image](https://user-images.githubusercontent.com/8676443/87570914-96dccb80-c6c9-11ea-8b0a-52a8129af882.png)

- Process Hacker shows SecureUxTheme.dll to be loaded into winlogon.exe, like this:

![image](https://user-images.githubusercontent.com/8676443/87570980-acea8c00-c6c9-11ea-9aa9-d9002c944b77.png)

**Comment by namazso** [comment] 2020-07-15 17:19
Seems to work perfectly on a freshly installed 2004 VM, with all possible security features enabled

![image](https://user-images.githubusercontent.com/8676443/87575325-0b1a6d80-c6d0-11ea-9e6c-2525a1bb78ec.png)

**Comment by Darkorz** [comment] 2020-07-16 04:17
Thanks for testing. Seems like the problem is on my end then. Tested what you asked & there seems to be a problem with permissions. Any idea how to solve it?

![0](https://user-images.githubusercontent.com/43709602/87625936-a7be2900-c72b-11ea-97ab-842ec26ae92f.PNG)
![1](https://user-images.githubusercontent.com/43709602/87625943-abea4680-c72b-11ea-9a6c-cfe7cad25c6e.PNG)
![3](https://user-images.githubusercontent.com/43709602/87625965-b9073580-c72b-11ea-984c-6295097d8398.PNG)

**Comment by namazso** [comment] 2020-07-16 04:35
run Process Hacker as administrator. If you already did and it still doesn't show, screenshot the "General" tab.

**Comment by Darkorz** [comment] 2020-07-16 04:39
![1](https://user-images.githubusercontent.com/43709602/87627492-27012c00-c72f-11ea-89a9-7b82b5f2240d.PNG)

**Comment by namazso** [comment] 2020-07-16 04:45
okay, this probably means that something is acting up with theme applying, since custom themes should be allowed to load. My guess in #14 was that there's possibly some WoW64 messup going on. I'll post an x64 build of themetool in a few mins.

**Comment by namazso** [comment] 2020-07-16 05:00
okay, could you try this one? It's just an x64 compile of ThemeTool straight from repo.
[ThemeTool.zip](https://github.com/namazso/SecureUxTheme/files/4929399/ThemeTool.zip)

If it still doesn't work, could you try the [old method](https://github.com/namazso/SecureUxTheme/wiki/Help:-Step-by-step-installing-SecureUxTheme-and-a-custom-theme-(old))?

**Comment by Darkorz** [comment] 2020-07-16 05:12
x64 did not work. The old method however did work. Thank you!

**Comment by namazso** [comment] 2020-07-16 05:14
Thanks for feedback!
I'll try to figure out what could be the issue.
Can I ask if you ran ThemeTool originally as standalone (and if so, as administrator?), or from installer?

**Comment by Darkorz** [comment] 2020-07-16 05:16
I ran it from the installer. Originally without admin but when it didn't work I reinstalled it and tried with admin and it didn't seem to make a difference. Again, thanks a lot for helping out.

**Comment by bennibennibenni** [comment] 2020-08-13 11:04
any update about this issues?It happend to me too. Themetool success apply the them when first intall. But revert back to default them after restart

Windows 10 19041

**Comment by namazso** [comment] 2020-08-13 18:34
@bennibennibenni i'm running same build and it works on my machine. fixes or changes are not planned for this major version of the tooling, eventually the branch `custom_installer` will replace everything. It has logging, more sanity checks, etc..
Theme setting works already so feel free to compile it yourself to try. Installing is still half-implemented though.

**Comment by namazso** [comment] 2020-08-20 23:10
probably fixed in v2.0 will reopen if it still isn't

**Closed by namazso** 2020-08-20 23:10 UTC
